using Config.Net;

namespace DiscordClient.Configuration;

public static class ConfigManager
{
    public static IBotConfig BotConfig { get; private set; } = null!;


    public static void Initialize()
    {
        Logger.Info("Initializing configuration...");
        
        // Create necessary directories.
        DirectoryInfo configDirectory = Directory.CreateDirectory("config");
        
        // Bot configuration
        string botConfigPath = Path.Combine(configDirectory.FullName, "config_bot.json");
        BotConfig = new ConfigurationBuilder<IBotConfig>()
            .UseJsonFile(botConfigPath)
            .Build();

        if (!File.Exists(botConfigPath))
        {
            // Force the config file to be regenerated by setting a value in the config.
            BotConfig.Token = BotConfig.Token;
            BotConfig.Owners = BotConfig.Owners;
            BotConfig.DumpTargetChannelName = BotConfig.DumpTargetChannelName;
            Logger.Warn("Bot configuration file not found. Generating a new one...");
        }
        
        Logger.Info("Configuration files initialized.");
    }
}